### ISSUE TITLE
Merging the results of K-order models with 5 covariates

### ISSUE THREAD

**Issue by seyiaros** [spatialstatisticsupna/bigDM#3]
Hello 

I am using the CAR_INLA function to fit a spatial model with a spatial domain of 6791 divided into 9 sub-regions. I am following your example of fitting spatial models but with a vector object of 5 covariates (X). The model runs fine from steps 1 - 2 but I get an error message "Error in checkforRemoteError(val): 10 nodes produced errors; first error: invalid 'row.names' length.  My model strategy is simplified.laplace and K = 1. I am not sure of why I am getting this error message. Thank you

**Comment by aritz-adin** [comment]
Dear @seyiaros,

Could you please send me a reproducible example in order to check what is happening?


Best,
Aritz

**Comment by seyiaros** [comment]
Dear Aritz

Thank you for getting back.  I resolved the issue - All the grouping variables should be of a character format variable: I initially had a numeric format grouping variable. 

Regards
Seyi

**Comment by aritz-adin** [comment]
Nice!

I will try to modify the code to accept numeric variables as grouping variables as well.


Best,
Aritz
